### ISSUE TITLE
Mint 20.3 calendar update needs themeing

### ISSUE THREAD

**Issue by 392781** [SebastJava/mint-themes#24]
There is an issue with the new calendar provided with Mint 20.3:

![image](https://user-images.githubusercontent.com/25296775/148624622-1427d861-1a86-435e-96a7-42d6f954a46e.png)

As you can see the left-hand side is not themed properly (and probably reverting to stock colors/gradients).  I'm guessing it's because the theme currently does not support it since the calendar update is a brand new feature.

**Comment by SebastJava** [comment]
>  I'm guessing it's because the theme currently does not support it since the calendar update is a brand new feature.

Yes, that's right.

**Tested:** Same issue with Mint-Y-Legacy-Aqua. I did a quick 5 minutes search, and was not able to locate where this green is coming from. Maybe there is a default green colour in this new calendar itself. And then, obviously, there is some specific specs to override this in this new Mint-Y-Aqua, but not in the old Mint-Y-Legacy-Aqua, or whatever colour you choose.

**Conclusion:** This will require further investigation.

**Comment by SebastJava** [comment]
Interestingly, i get the same green colour values when using a colour picker, here on your screenshot, and on my screenshot with the standard Mint-Y-Legacy-Aqua. So, it isn't anything specific to this Mint-Yz fork, I get the exact same results with the official legacy theme.

**Comment by SebastJava** [comment]
I am now working on the new Mint-Y. So, this is already done in the codings. :)
It will be available on the next release, coming up sometime before the end of this winter.
