### ISSUE TITLE
Ease of install on other distros

### ISSUE THREAD

**Issue by sanderseo** [SebastJava/mint-themes#35]
Hi @SebastJava ! Thank you so much for making this theme. I am on Manjaro Cinnamon, and the MintGum color is exactly right. Whole thing looks super nice. I installed from source without a hitch, but wanted to ask if there's something that makes it harder to package than the other themes/icons on Cinnamon-Look. Most let you either just copy files or run an install script. 

This is not a request for you to do more work. But having different install methods than source/.deb would make it more widely accessible to the Cinnamon users on other distros (Fedora, Arch, etc). If it's just a matter of time/someone taking initiative to add it to AUR, that would be great news. This is the first time I've had to put a theme together from source, so figured there might be a technical reason for it being packaged as such.

Lastly, you might want to revisit & standardize the DIY instructions between icons & theme. The icons DIY is harder to follow and gives less context. I knew which steps were relevant to me since I did the theme prior, but steps like cloning the repo should be added as well. Maybe having modification instructions separate from non-.deb install instructions could be a good idea. Great work. You can tell this had a lot of effort put into it.

**Comment by SebastJava** [comment]
@sanderseo Please excuse my ignorance. I have never tried anything else but Ubuntu based distributions, so far. For all Debian and Ubuntu based distributions, these Mint-Yz themes and icons are super easy to install, being available as a Debian package:

https://github.com/SebastJava/mint-yz-theme/releases/latest
https://github.com/SebastJava/mint-yz-icons/releases/latest

The source files and Do-It-Yourself instructions are only there for those who want to go much further and create their own themes. I also wrote these instructions for my own use, as i will probably need some reminder if i come back into this after being away for a long time. It sure is much more complicated, and possibly still incomplete.

So, if i got what you are saying correctly, you can't install a Debian package on Manjaro ? I wasn't aware of that. It wouldn't be hard for me to simply include a zip file containing all the `/usr/share/themes/Mint-Yz-*` files. I would also include a very simple installation script: erase all previous `/usr/share/themes/Mint-Yz-*` and then copy the new ones.

I will have to think about this, later. Frankly speaking, the timing is bad. Yes, as you said, that was really a lot of work. A big part of my winter time went into this. And now i really need to get out and walk away for a few days. But i should think about this sometime later. It should be easy to do.

P.S.: All the `/usr/share/themes/Mint-Yz-*` files are already there in the `mint-yz-theme_3.1_all.deb` package. If you can't install Debian packages automatically on other distros, i wonder if there is a way to simply extract those files from this Debian package, and then just copy them into `/usr/share/themes` ? Here on LinuxMint Cinnamon, a double-click is all it takes to install this package with the GDebi Package Installer, but i could also do a right-click to extract the files and then just copy them into `/usr/share/themes`. That's just quick thinking. Not tested yet. I don't know if you could simply do this right-click to extract on Manjaro. I could install Manjaro onto a virtual machine and test this sometime later.

**Comment by sanderseo** [comment]
@SebastJava Thank you for your rapid reply. I used the second half of your DIY guide (clone repo, run scripts, copy to themes folder) to install. Wasn't sure if extracting would work. 

The files-in-a-zip would be the ideal way to distribute this & icons via Cinnamon-look. Then it's entirely distro-agnostic. Script would be nice, but plenty of popular themes/icon packs lack one.

A lot of software packaged as RPM (Fedora, OpenSuse) or Deb is available on Arch/Manjaro via the AUR, since they can't be installed directly in those formats. 

The reason this is my first GitHub comment, is that your theme would (IMO) be the ideal default for Manjaro Cinnamon. Currently they have Papirus-Maia icons, Mint-Y-Dark-Teal theme. The Maia color found on Manjaro menu icon and folders matches your MintGum, whereas default Teal is thematically similar, but a much lighter color. 

I think if they replaced Maia folders with yours and set MintGum as default, the whole package would be totally on-point. The beautiful Cinnamon folders, matching theme colors, and familiarity of Papirus for Manjaro users. Perfect balance of familiar and different from Mint Cinnamon.

**Comment by SebastJava** [comment]
@sanderseo 
* I added zip files to the latest releases on both https://github.com/SebastJava/mint-yz-theme#readme and https://github.com/SebastJava/mint-yz-icons#readme
* I updated the readme files on both theme and icons. It looks a bit complicated and/or confusing because you get instructions for both Debian and ZIP files. I will probably stop making Debian packages on the future releases, and remove these Debian instructions from the readme files.
* I'm embarrassed to say that there's probably still a new version coming out soon. I constantly change my ideas about colors. Just small and subtle improvements. For both the themes and icons. See here: https://github.com/SebastJava/mint-yz-theme/blob/master/Mint-Y-Colors/Mint-Y-Variations-next.png This file is constantly changing and will probably disappear soon, being renamed to a new Mint-Y-Variations.png

Feedback would be appreciated, when you have some spare time.

**Comment by SebastJava** [comment]
I still need to update the Do-It-Yourself files. Include the simple ZIP packaging method and remove the Debian packaging method.

**Comment by SebastJava** [comment]
UPDATES ON https://github.com/SebastJava/mint-yz-icons

* update-cache.sh echos: "Done or else just don't worry..."
* README.md: updates on installation instructions

P.S.: It still looks a bit complicated. As said before, I will stop making Debian packages, and then the readme install instructions won't be offering multiple choices. This will look cleaner, shorter, and less confusing.

**Comment by SebastJava** [comment]
All done, on both Mint-Yz themes and icons
**version 3.2 released now**

changelog:
* Downgraded packaging method to a simple and universal ZIP file.
* Color names got changed: Aqua, Red, Orange.
* Subtle color updates on Aqua, BlueElectron, BlueBelize.
* Updated README and Do-It-Yourself files.
