### ISSUE TITLE
(LM21) Broken titlebars when snapping.

### ISSUE THREAD

**Issue by JulianHeuser** [SebastJava/mint-themes#42]
**Describe the bug**  
Snapping a window then unfocusing it causes the titlebar to appear offset. This doesn't happen with gtk stuff (calculator, calendar, etc.), only programs with a standard titlebar.

**This bug comes from my Mint-Yz or their Mint-Y ?**  
This doesn't occur with the Mint-Y theme.

**To Reproduce**  
1. Open a window (file manager, terminal, etc.).
2. Snap it to the side or a corner.
3. Unfocus it by clicking somewhere else.

**Expected behavior**  

**Screenshots**  
![image](https://user-images.githubusercontent.com/25406449/183961989-78f695d0-c942-452a-be5b-7ee39d9e76a9.png)

**Desktop (please complete the following information):**  
 - OS: Linux Mint
 - OS Version 21
 - Desktop Environment: Cinnamon

**Comment by SebastJava** [comment]
I know. These Mint-Yz are not ready for LM 21. I must do a major update from the upstream source. I will be working on this later this month...

**Comment by SebastJava** [comment]
Fixed with new release v4.0

**Comment by JulianHeuser** [comment]
Thank you for your work!
